package mediFind.model;

public class Insurance {

	protected int insuranceId;
	protected String name;
		
	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the insuranceId.
	public Insurance(int insuranceId, String name) {
		this.insuranceId = insuranceId;
		this.name = name;
		
	}
	
	// This constructor can be used for reading records from MySQL, where we only have the insuranceId,
	// such as a foreign key reference to insuranceId.
	public Insurance(int insuranceId) {
		this.insuranceId = insuranceId;
	}
	
	// This constructor can be used for creating new records, where the insuranceId may not be
	// assigned yet since it is auto-generated by MySQL.

	public Insurance(String name) { 
		this.name = name;
	}
	
	
	public int getInsuranceId() {
		return insuranceId;
	}

	public void setInsuranceId(int insuranceId) {
		this.insuranceId = insuranceId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
