package mediFind.model;

public class Owners {

	protected int ownerId;
	protected String ownerName;
	
	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the ownerId.
	public Owners(int ownerId, String ownerName) {
		this.ownerId = ownerId;
		this.ownerName = ownerName;
	}
	
	// This constructor can be used for reading records from MySQL, where we only have the ownerId,
	public Owners(int ownerId) {
		this.ownerId = ownerId;
	}

	// This constructor can be used for creating new records, where the ownerId may not be
	// assigned yet since it is auto-generated by MySQL.
	public Owners(String ownerName) {
		this.ownerName = ownerName;
	} 
	
	/** Getters and setters. */
	
	public int getOwnerId() {
		return ownerId;
	}

	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}
	
	public String getOwnerName() {
		return ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}
}
