package mediFind.model;

public class Address {
	protected int addressId;
	protected AddressType addressType;
	protected String street;
	protected String city;
	protected String state;
	protected int zipCode;
	
	public enum AddressType {
		Hospital, User
	}
	
	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the addressId.
	public Address (int addressId, String addressType, String street, String city, String state, int zipCode) {
		this.addressId = addressId;
		this.addressType = AddressType.valueOf(AddressType.class, addressType);
		this.street = street;
		this.city = city; 
		this.state = state;
		this.zipCode = zipCode;

	}
	
	// This constructor can be used for reading records from MySQL, where we only have the addressId,
	public Address(int addressId) {
		this.addressId = addressId;
	}

	
	// This constructor can be used for creating new records, where the addressId may not be
	// assigned yet since it is auto-generated by MySQL.
	public Address (AddressType addressType, String street, String city, String state, int zipCode) {
		this.addressType = addressType;
		this.street = street;
		this.city = city;
		this.state = state;
		this.zipCode = zipCode;}
	
	public Address(String street, String city, String state, int zip) {
		this.street = street;
		this.city = city;
		this.state = state;
		this.zipCode = zip;
	}

	/** Getters and setters. */	
	public int getAddressId() {
		return addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}
	
	public AddressType getAddressType() {
		return addressType;
	}

	public void setAddressType(AddressType addressType) {
		this.addressType = addressType;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}
	
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}
	
	public int getZipCode() {
		return zipCode;
	}

	public void setZipCode(int zipCode) {
		this.zipCode = zipCode;
	}

}
